### ISSUE TITLE
Wilddog is not constructor

### ISSUE THREAD

**Issue by XiaoxiongLiu** [WildDogTeam/demo-js-wild-reactnative#2]
按照文档创建了新项目 ， 引用了wilddog， 启动显示 getRef方法  Wilddog is not a constructor

**Comment by dongkai1993-zz** [comment]
这个问题是由于npm install 下载了2.0.0+版本的SDK，wilddog初始化的方式发生了变化。
解决方法：参考最新的 index.ios.js
